###########################################################
##Fonts####################################################
###########################################################

font:
  normal:
     family: SauceCodePro Nerd Font
     style: Regular
  bold:
     family: SauceCodePro Nerd Font
     style: Bold
  italic:
     family: SauceCodePro Nerd Font
     style: Italic
  bold_italic:
     family: SauceCodePro Nerd Font
     style: Bold Italic
  size: 9


###########################################################
##Key bindings#############################################
###########################################################

key_bindings:
  - { key: V,        mods: Control, action: Paste            }
  - { key: C,        mods: Control, action: Copy             }
  - { key: Key0,     mods: Control,       action: ResetFontSize    }
  - { key: Equals,   mods: Control,       action: IncreaseFontSize }
  - { key: Plus,     mods: Control,       action: IncreaseFontSize }
  - { key: Minus,    mods: Control,       action: DecreaseFontSize }
  - { key: Minus,    mods: Control,       action: DecreaseFontSize }

###########################################################
##Colors###################################################
###########################################################

# Copyright (c) 2017-present Arctic Ice Studio <development@arcticicestudio.com>
# Copyright (c) 2017-present Sven Greb <code@svengreb.de>

# Project:    Nord Alacritty
# Version:    0.1.0
# Repository: https://github.com/arcticicestudio/nord-alacritty
# License:    MIT
# References:
#   https://github.com/alacritty/alacritty

colors:
  primary:
    background: '#212129'
    foreground: '#e5eaf0'
    dim_foreground: '#a5abb6'
  cursor:
    text: '#2e3440'
    cursor: '#d8dee9'
  vi_mode_cursor:
    text: '#2e3440'
    cursor: '#d8dee9'
  selection:
    text: CellForeground
    background: '#4c566a'
  search:
    matches:
      foreground: CellBackground
      background: '#88c0d0'
    bar:
      background: '#434c5e'
      foreground: '#d8dee9'
  normal:
    black: '#3b4252'
    red: '#bf616a'
    green: '#a3be8c'
    yellow: '#ebcb8b'
    blue: '#81a1c1'
    magenta: '#b48ead'
    cyan: '#88c0d0'
    white: '#e5e9f0'
  bright:
    black: '#4c566a'
    red: '#bf616a'
    green: '#a3be8c'
    yellow: '#ebcb8b'
    blue: '#81a1c1'
    magenta: '#b48ead'
    cyan: '#8fbcbb'
    white: '#eceff4'
  dim:
    black: '#373e4d'
    red: '#94545d'
    green: '#809575'
    yellow: '#b29e75'
    blue: '#68809a'
    magenta: '#8c738c'
    cyan: '#6d96a5'
    white: '#aeb3bb'

###########################################################
##Options##################################################
###########################################################

env:
  TERM: xterm-256color

window:
  padding:
    x: 3
    y: 3

dpi:
  x: 96.0
  y: 96.0

background_opacity: 0.7
live_config_reload: true
draw_bold_text_with_bright_colors: true

###########################################################
###########################################################
###########################################################
