#!/bin/bash

sudo btrfs property set -ts /.snapshots/1/snapshot/ ro false
sudo btrfs property set -ts /.snapshots/2/snapshot/ ro false
sudo btrfs property set -ts /.snapshots/3/snapshot/ ro false
sudo btrfs property set -ts /.snapshots/4/snapshot/ ro false
sudo btrfs property set -ts /.snapshots/5/snapshot/ ro false
sudo btrfs property set -ts /.snapshots/6/snapshot/ ro false
sudo btrfs property set -ts /.snapshots/7/snapshot/ ro false
sudo btrfs property set -ts /.snapshots/8/snapshot/ ro false
sudo btrfs property set -ts /.snapshots/9/snapshot/ ro false
sudo btrfs property set -ts /.snapshots/10/snapshot/ ro false
sudo btrfs property set -ts /.snapshots/11/snapshot/ ro false
sudo btrfs property set -ts /.snapshots/12/snapshot/ ro false
sudo btrfs property set -ts /.snapshots/13/snapshot/ ro false
sudo btrfs property set -ts /.snapshots/14/snapshot/ ro false
sudo btrfs property set -ts /.snapshots/15/snapshot/ ro false
sudo btrfs property set -ts /.snapshots/16/snapshot/ ro false
sudo btrfs property set -ts /.snapshots/17/snapshot/ ro false
sudo btrfs property set -ts /.snapshots/18/snapshot/ ro false
sudo btrfs property set -ts /.snapshots/19/snapshot/ ro false
sudo btrfs property set -ts /.snapshots/20/snapshot/ ro false
sudo btrfs property set -ts /.snapshots/21/snapshot/ ro false
sudo btrfs property set -ts /.snapshots/22/snapshot/ ro false
sudo btrfs property set -ts /.snapshots/23/snapshot/ ro false
sudo btrfs property set -ts /.snapshots/24/snapshot/ ro false
sudo btrfs property set -ts /.snapshots/25/snapshot/ ro false
sudo btrfs property set -ts /.snapshots/26/snapshot/ ro false
sudo btrfs property set -ts /.snapshots/27/snapshot/ ro false
sudo btrfs property set -ts /.snapshots/28/snapshot/ ro false
sudo btrfs property set -ts /.snapshots/29/snapshot/ ro false
sudo btrfs property set -ts /.snapshots/30/snapshot/ ro false
sudo btrfs property set -ts /.snapshots/31/snapshot/ ro false
sudo btrfs property set -ts /.snapshots/32/snapshot/ ro false
sudo btrfs property set -ts /.snapshots/33/snapshot/ ro false
sudo btrfs property set -ts /.snapshots/34/snapshot/ ro false
sudo btrfs property set -ts /.snapshots/35/snapshot/ ro false
sudo btrfs property set -ts /.snapshots/36/snapshot/ ro false
sudo btrfs property set -ts /.snapshots/37/snapshot/ ro false
sudo btrfs property set -ts /.snapshots/38/snapshot/ ro false
sudo btrfs property set -ts /.snapshots/39/snapshot/ ro false
sudo btrfs property set -ts /.snapshots/40/snapshot/ ro false
sudo btrfs property set -ts /.snapshots/41/snapshot/ ro false
sudo btrfs property set -ts /.snapshots/42/snapshot/ ro false
sudo btrfs property set -ts /.snapshots/43/snapshot/ ro false
sudo btrfs property set -ts /.snapshots/44/snapshot/ ro false
sudo btrfs property set -ts /.snapshots/45/snapshot/ ro false
sudo btrfs property set -ts /.snapshots/46/snapshot/ ro false
sudo btrfs property set -ts /.snapshots/47/snapshot/ ro false
sudo btrfs property set -ts /.snapshots/48/snapshot/ ro false
sudo btrfs property set -ts /.snapshots/49/snapshot/ ro false
sudo btrfs property set -ts /.snapshots/50/snapshot/ ro false
sudo btrfs property set -ts /.snapshots/51/snapshot/ ro false
sudo btrfs property set -ts /.snapshots/52/snapshot/ ro false
sudo btrfs property set -ts /.snapshots/53/snapshot/ ro false
sudo btrfs property set -ts /.snapshots/54/snapshot/ ro false
sudo btrfs property set -ts /.snapshots/55/snapshot/ ro false
sudo btrfs property set -ts /.snapshots/56/snapshot/ ro false
sudo btrfs property set -ts /.snapshots/57/snapshot/ ro false
sudo btrfs property set -ts /.snapshots/58/snapshot/ ro false
sudo btrfs property set -ts /.snapshots/59/snapshot/ ro false
sudo btrfs property set -ts /.snapshots/60/snapshot/ ro false
sudo btrfs property set -ts /.snapshots/61/snapshot/ ro false
sudo btrfs property set -ts /.snapshots/62/snapshot/ ro false
sudo btrfs property set -ts /.snapshots/63/snapshot/ ro false
sudo btrfs property set -ts /.snapshots/64/snapshot/ ro false
sudo btrfs property set -ts /.snapshots/65/snapshot/ ro false
sudo btrfs property set -ts /.snapshots/66/snapshot/ ro false
sudo btrfs property set -ts /.snapshots/67/snapshot/ ro false
sudo btrfs property set -ts /.snapshots/68/snapshot/ ro false
sudo btrfs property set -ts /.snapshots/69/snapshot/ ro false
sudo btrfs property set -ts /.snapshots/70/snapshot/ ro false
sudo btrfs property set -ts /.snapshots/71/snapshot/ ro false
sudo btrfs property set -ts /.snapshots/72/snapshot/ ro false
sudo btrfs property set -ts /.snapshots/73/snapshot/ ro false
sudo btrfs property set -ts /.snapshots/74/snapshot/ ro false
sudo btrfs property set -ts /.snapshots/75/snapshot/ ro false
sudo btrfs property set -ts /.snapshots/76/snapshot/ ro false
sudo btrfs property set -ts /.snapshots/77/snapshot/ ro false
sudo btrfs property set -ts /.snapshots/78/snapshot/ ro false
sudo btrfs property set -ts /.snapshots/79/snapshot/ ro false
sudo btrfs property set -ts /.snapshots/80/snapshot/ ro false
sudo btrfs property set -ts /.snapshots/81/snapshot/ ro false
sudo btrfs property set -ts /.snapshots/82/snapshot/ ro false
sudo btrfs property set -ts /.snapshots/83/snapshot/ ro false
sudo btrfs property set -ts /.snapshots/84/snapshot/ ro false
sudo btrfs property set -ts /.snapshots/85/snapshot/ ro false
sudo btrfs property set -ts /.snapshots/86/snapshot/ ro false
sudo btrfs property set -ts /.snapshots/87/snapshot/ ro false
sudo btrfs property set -ts /.snapshots/88/snapshot/ ro false
sudo btrfs property set -ts /.snapshots/89/snapshot/ ro false
sudo btrfs property set -ts /.snapshots/90/snapshot/ ro false
sudo btrfs property set -ts /.snapshots/91/snapshot/ ro false
sudo btrfs property set -ts /.snapshots/92/snapshot/ ro false
sudo btrfs property set -ts /.snapshots/93/snapshot/ ro false
sudo btrfs property set -ts /.snapshots/94/snapshot/ ro false
sudo btrfs property set -ts /.snapshots/95/snapshot/ ro false
sudo btrfs property set -ts /.snapshots/96/snapshot/ ro false
sudo btrfs property set -ts /.snapshots/97/snapshot/ ro false
sudo btrfs property set -ts /.snapshots/98/snapshot/ ro false
sudo btrfs property set -ts /.snapshots/99/snapshot/ ro false
sudo btrfs property set -ts /.snapshots/100/snapshot/ ro false
