#! /bin/sh

###########################################################
##Depencies################################################
###########################################################

# bspwm
# sxhkd
# i3lock
# kitty
# polybar (AUR)
# picom-jonaburg-git (AUR)
# nitrogen
# dmenu
# lxsession
# xorg-xbacklight
# xorg-xinput
# lm_sensors
# scrot

# firefox (keybindings)
# pcmanfm (keybindings)
# spotify (keybindings)
# discord (keybindings)
# calcurse (keybindings)

###########################################################
##Startup applications#####################################
###########################################################

# pgrep -x sxhkd > /dev/null || sxhkd &
sxhkd &
setxkbmap pl &
xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Tapping Enabled" 1 &

picom --experimental-backends --config=/home/jan/.config/picom/picom-bspwm.conf &
feh --bg-scale /usr/share/wallpapers/75.jpg &
polybar example --config=/home/jan/.config/polybar/config-bspwm &

lxsession &
tlp start &

/home/jan/.scripts/btrfs.sh &

# /home/jan/.config/polybar/launch-bspwm.sh


###########################################################
##BSPWM configuration######################################
###########################################################

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config window_gap          10

bspc config split_ratio          	0.50
bspc config borderless_monocle   	false
bspc config gapless_monocle      	false
bspc config focus_follows_pointer	true

bspc config click_to_focus              false
bspc config pointer_modifier 		mod4
bspc config pointer_action1		move
bspc config pointer_action2 		resize_side
bspc config pointer_action3 		resize_corner

bspc config focused_border_color	"#eacb8b"
bspc config normal_border_color		"#4f4f4f"
bspc config active_border_color		"#4f4f4f"
bspc config urgent_border_color		"#4f4f4f"

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off

###########################################################
###########################################################
###########################################################
